version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "gradio.egg-info/requires.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r gradio.egg-info/requires.txt
            pip install selenium==4.0.0a6.post2
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "gradio.egg-info/requires.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            mkdir /tmp/artifacts/
      - run:
          command: |
            . venv/bin/activate
            echo $PWD
            python3 -m unittest
      - store_artifacts:
          path: /tmp/artifacts
          destination: screenshots
      - store_test_results:
          path: test-reports/